./cloud-torrent_linux_amd64 --help

  Usage: cloud-torrent_linux_amd64 [options]

  Options:
  --title, -t             Title of this instance (default SimpleTorrent, env TITLE)
  --port, -p              Listening port (default 3000, env PORT)
  --host, -h              Listening interface (default all, env HOST)
  --unix-perm, -u         DomainSocket file permission (default 0666, env UNIXPERM)
  --auth, -a              Optional basic auth in form 'user:password' (env AUTH)
  --proxy-url             Proxy url (env PROXY_URL)
  --config-path, -c       Configuration file path (default /etc/cloud-torrent.yaml)
  --key-path, -k          TLS Key file path
  --cert-path, -r         TLS Certicate file path
  --rest-api              Listen on a trusted port accepts /api/ requests (eg. localhost:3001, env RESTAPI)
  --log, -l               Enable request logging
  --open, -o              Open now with your default browser
  --disable-log-time, -d  Don't print timestamp in log
  --debug                 Debug app
  --debug-torrent         Debug torrent engine
  --conv-yaml             Convert old json config to yaml format.
  --version, -v           display version
  --help                  display help

  Version:
    0.0.0

  Read more:
    https://github.com/boypt/simple-torrent